#!/bin/sh

MVN_PACKAGE_DIR=apache-maven-3.0.5
MVN_PACKAGE_VER=${MVN_PACKAGE_DIR}-bin.tar.gz

LLVM_PACKAGE_DIR=llvm-3.3.src
LLVM_PACKAGE_VER=${LLVM_PACKAGE_DIR}.tar.gz

BOOST_PACKAGE_DIR=boost_1_46_1
BOOST_PACKAGE_VER=${BOOST_PACKAGE_DIR}.tar.gz

IMPALA_PACKAGE_DIR=impala-2.2.0-cdh5.4.4
IMPALA_PACKAGE_VER=${IMPALA_PACKAGE_DIR}-src.tar.gz
