#!/bin/sh

# Spark installation package
# SPARK_PACKAGE_DL_URL=http://d3kbcqa49mib13.cloudfront.net/spark-1.6.0-bin-hadoop2.6.tgz
SPARK_PACKAGE_DL_URL=

SPARK_MASTER_PORT=7077
SPARK_MASTER_WEBUI_PORT=8085
SPARK_WORKER_WEBUI_PORT=8086
SPARK_WORKER_INSTANCES=6
SPARK_WORKER_MEMORY=10g

SPARK_EXECUTOR_MEMORY=8000M
SPARK_DRIVER_MEMORY=9000M
